import { test, expect } from "@playwright/test";
import * as H from "./util";

// =============================================================================
// Layout-persistence regression gate — proves the Dockview tiling round-trips
// through a page reload AND that a poisoned saved layout is rejected.
//
// Mechanism under test (src/dockview/layoutPersistence.ts):
//   SAVE   — debounced api.toJSON() → localStorage["vh-host:layout:v1"], hooked
//            on Dockview's onDidLayoutChange (runtime ops mutate the live tree;
//            the save only serializes the result).
//   RESTORE — cold init reads localStorage, VALIDATES every pane url through the
//            SAME isFleetEntry http/https guard the fleet resolver uses, REPAIRS
//            (drops invalid panes from the tree), and calls api.fromJSON() exactly
//            ONCE (COLD ONLY — it reloads every iframe; runtime never calls it).
//
// PRECEDENCE under test: saved-layout-wins-with-validation; fleet/mock seed is
// the fallback when no valid saved layout exists.
//
// Playwright gives each test() a fresh browser context, so localStorage is EMPTY
// at the start of every test unless a test explicitly pre-seeds it (via
// addInitScript). The survival/shell gates therefore see no saved layout and cold
// restore falls back to seed — they are unaffected (verified separately).
//
// Runs on Chromium AND Firefox (webkit is launch-blocked locally; see the default
// lane's project set).
// =============================================================================

test.describe("layout persistence", () => {
  test("saved layout round-trips through reload (panes restored with same urls/labels)", async ({
    page,
  }) => {
    // Fresh context → no localStorage → seed loads as today.
    await H.loadHost(page);

    // Mutate the layout so the persisted state differs from the default seed (a
    // split adds a pane whose {url,label} is generated by nextMockPane).
    const seedIds = await H.panes(page);
    const newId = await H.split(page, seedIds[0], "right");
    expect(newId, "split created a new pane").toBeTruthy();
    await H.waitForReady(page, newId!);

    // Capture the post-mutation layout — the state we expect to persist.
    const expected = await H.paneParams(page);
    const expectedById = new Map(expected.map((p) => [p.id, p]));
    expect(expected.length, "layout has the split pane").toBe(seedIds.length + 1);

    // Flush the debounced save to localStorage before reloading.
    await H.waitForSavedLayout(page, expected.length);

    // Reload → cold restore reads localStorage (fromJSON, exactly once). The
    // restored iframes are FRESH (fromJSON recreates them) — that is allowed here
    // because this is cold init, before any iframe had a live identity.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(expected.length);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
    const restored = await H.paneParams(page);

    // The restored layout matches: same pane count + every restored id carries
    // the exact {url,label} it had before the reload (ids are stable across
    // fromJSON — dockview's deserializer reuses the saved panel ids verbatim).
    expect(restored.length, "restored pane count matches").toBe(expected.length);
    for (const r of restored) {
      const e = expectedById.get(r.id);
      expect(e, `restored pane ${r.id} existed before reload`).toBeDefined();
      expect(r.url, `restored pane ${r.id} url unchanged`).toBe(e!.url);
      expect(r.label, `restored pane ${r.id} label unchanged`).toBe(e!.label);
    }
  });

  test("NEGATIVE: a poisoned saved layout (javascript: url) is rejected on cold restore", async ({
    page,
  }) => {
    // Start from a REAL, well-formed layout (captured from the live api) so the
    // poisoned blob is otherwise structurally valid — the restore must reject it
    // for the POISON, not for a shape defect. A hand-rolled tree would conflate
    // the two failure modes.
    await H.loadHost(page);
    const state = await H.serialize(page);
    const panels = (state.panels ?? {}) as Record<
      string,
      { params?: { url?: string; label?: string } }
    >;
    const ids = Object.keys(panels);
    expect(ids.length, "seed layout has panels to poison").toBeGreaterThanOrEqual(2);

    // Poison ONE panel's url with a javascript: scheme. This MUST NEVER reach an
    // unsandboxed iframe.src — it would execute same-origin against the host
    // shell. The restore must DROP this panel (defense-in-depth: never trust
    // stored data; the url goes to an unsandboxed iframe.src).
    const victim = ids[ids.length - 1];
    panels[victim].params = { url: "javascript:alert(document.domain)", label: "evil" };

    // Pre-seed the poisoned layout into the host origin's localStorage (the page
    // is currently at :5173 from loadHost), then reload so the app's cold
    // restore reads the poisoned blob. (addInitScript is avoided because it also
    // runs in every child iframe — the cross-origin mock panes on :5174 — which
    // is the wrong origin; writing on the live :5173 page then reloading is
    // unambiguous and scopes to the host origin only.)
    await page.evaluate(
      ({ payload, key }) => {
        localStorage.setItem(key, JSON.stringify(payload));
      },
      { payload: state, key: H.LAYOUT_STORAGE_KEY },
    );

    // Cold load: the poisoned panel is DROPPED by restore validation; the
    // remaining valid panels are restored (mirrors the F1 fleet-guard pattern:
    // drop the bad entry, keep the good ones; fall back to seed only if that
    // empties it).
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ids.length - 1);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // SECURITY: no iframe points at the poisoned url (or any non-http scheme).
    const srcs = await H.iframeSrcs(page);
    expect(
      srcs.every((s) => !/^javascript:/i.test(s)),
      "no javascript: iframe src after poisoned restore",
    ).toBe(true);

    // The poisoned panel was dropped; every restored url is http/https.
    const restored = await H.paneParams(page);
    expect(
      restored.find((p) => p.id === victim),
      "poisoned panel was not restored",
    ).toBeUndefined();
    expect(
      restored.every((p) => /^https?:/i.test(p.url)),
      "restored urls are all http/https",
    ).toBe(true);
  });
});
