import { test, expect } from "@playwright/test";
import * as H from "./util";

// =============================================================================
// Layout-persistence regression gate (multi-workspace v3 fractional schema) —
// proves the Dockview tiling round-trips through a page reload AND that a
// poisoned saved layout is rejected.
//
// Mechanism under test (src/dockview/layoutPersistence.ts):
//   SAVE   — debounced, serializes EVERY workspace's api.toJSON() into the v3
//            blob localStorage["vh-host:layout:v3"] =
//              { v: 3, activeWorkspaceId, workspaces: [{id, name, layout}] }
//            where each grid child stores `fraction` (share of its parent
//            branch) instead of dockview's px `size`; hooked on any
//            workspace's onDidLayoutChange + workspace add/close/switch.
//   RESTORE — cold init reads the v3 blob (hash → v3 key → legacy v2 key,
//            migrating px→fractions in-memory), materializes px = fraction ×
//            the CURRENT container extent, validates every workspace's every
//            pane url through the SAME isFleetEntry http/https guard the fleet
//            resolver uses, REPAIRS (drops invalid panes per workspace), and
//            calls api.fromJSON() exactly ONCE PER WORKSPACE (COLD ONLY — it
//            reloads every iframe in that workspace; runtime never calls it).
//
// PRECEDENCE under test: saved-layout-wins-with-validation; fleet/mock seed is
// the fallback for the default workspace when no valid blob exists.
//
// Playwright gives each test() a fresh browser context, so localStorage is EMPTY
// at the start of every test unless a test explicitly pre-seeds it. The
// survival/shell gates therefore see no blob and cold restore falls back to
// seed — they are unaffected (verified separately).
//
// Runs on Chromium AND Firefox (webkit is launch-blocked locally; see the default
// lane's project set).
// =============================================================================

/** Wrap a serialized Dockview layout in the workspace envelope as the default
 *  workspace (ws-1), so a pre-seeded blob matches what the app cold-restores.
 *  The default workspace id on a fresh context is "ws-1" (nextWsId starts at 1).
 *  Deliberately carries NO `v: 3` marker — the payload is raw dockview px
 *  output, exactly like a legacy v2-era blob, so the read path MIGRATES it
 *  (px→fractions) like real legacy data while keeping this test otherwise
 *  structurally valid (the poison test rejects for the POISON, not shape). */
function wrapLayout(layout: Record<string, unknown>): {
  activeWorkspaceId: string;
  workspaces: Array<{ id: string; name: string; layout: Record<string, unknown> }>;
} {
  return {
    activeWorkspaceId: "ws-1",
    workspaces: [{ id: "ws-1", name: "Workspace 1", layout }],
  };
}

test.describe("layout persistence", () => {
  test("saved layout round-trips through reload (panes restored with same urls/labels)", async ({
    page,
  }) => {
    // Fresh context → no localStorage → seed loads as today.
    await H.loadHost(page);

    // Mutate the layout so the persisted state differs from the default seed (a
    // split adds a pane whose {url,label} is generated by nextMockPane).
    const seedIds = await H.panes(page);
    const newId = await H.split(page, seedIds[0], "right");
    expect(newId, "split created a new pane").toBeTruthy();
    await H.waitForReady(page, newId!);

    // Capture the post-mutation layout — the state we expect to persist.
    const expected = await H.paneParams(page);
    const expectedById = new Map(expected.map((p) => [p.id, p]));
    expect(expected.length, "layout has the split pane").toBe(seedIds.length + 1);

    // Flush the debounced save to localStorage before reloading.
    await H.waitForSavedLayout(page, expected.length);

    // Reload → cold restore reads localStorage (fromJSON, exactly once per ws).
    // The restored iframes are FRESH (fromJSON recreates them) — that is allowed
    // here because this is cold init, before any iframe had a live identity.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(expected.length);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
    const restored = await H.paneParams(page);

    // The restored layout matches: same pane count + every restored id carries
    // the exact {url,label} it had before the reload (ids are stable across
    // fromJSON — dockview's deserializer reuses the saved panel ids verbatim).
    expect(restored.length, "restored pane count matches").toBe(expected.length);
    for (const r of restored) {
      const e = expectedById.get(r.id);
      expect(e, `restored pane ${r.id} existed before reload`).toBeDefined();
      expect(r.url, `restored pane ${r.id} url unchanged`).toBe(e!.url);
      expect(r.label, `restored pane ${r.id} label unchanged`).toBe(e!.label);
    }
  });

  test("NEGATIVE: a poisoned saved layout (javascript: url) is rejected on cold restore", async ({
    page,
  }) => {
    // Start from a REAL, well-formed layout (captured from the live api) so the
    // poisoned blob is otherwise structurally valid — the restore must reject it
    // for the POISON, not for a shape defect. A hand-rolled tree would conflate
    // the two failure modes.
    await H.loadHost(page);
    const state = await H.serialize(page);
    const panels = (state.panels ?? {}) as Record<
      string,
      { params?: { url?: string; label?: string } }
    >;
    const ids = Object.keys(panels);
    expect(ids.length, "seed layout has panels to poison").toBeGreaterThanOrEqual(2);

    // Poison ONE panel's url with a javascript: scheme. This MUST NEVER reach an
    // unsandboxed iframe.src — it would execute same-origin against the host
    // shell. The restore must DROP this panel (defense-in-depth: never trust
    // stored data; the url goes to an unsandboxed iframe.src).
    const victim = ids[ids.length - 1];
    panels[victim].params = { url: "javascript:alert(document.domain)", label: "evil" };

    // Wrap in the workspace envelope (default workspace ws-1) so the app
    // cold-restores this workspace, then pre-seed it into the host origin's
    // localStorage. (addInitScript is avoided because it also runs in every
    // child iframe — the cross-origin mock panes on :5174 — which is the wrong
    // origin; writing on the live :5173 page then reloading is unambiguous and
    // scopes to the host origin only.)
    const payload = wrapLayout(state);
    await page.evaluate(
      ({ payload, key }) => {
        localStorage.setItem(key, JSON.stringify(payload));
      },
      { payload, key: H.LAYOUT_STORAGE_KEY },
    );

    // Cold load: the poisoned panel is DROPPED by restore validation; the
    // remaining valid panels are restored (mirrors the F1 fleet-guard pattern:
    // drop the bad entry, keep the good ones; fall back to seed only if that
    // empties it).
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ids.length - 1);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // SECURITY: no iframe points at the poisoned url (or any non-http scheme).
    const srcs = await H.iframeSrcs(page);
    expect(
      srcs.every((s) => !/^javascript:/i.test(s)),
      "no javascript: iframe src after poisoned restore",
    ).toBe(true);

    // The poisoned panel was dropped; every restored url is http/https.
    const restored = await H.paneParams(page);
    expect(
      restored.find((p) => p.id === victim),
      "poisoned panel was not restored",
    ).toBeUndefined();
    expect(
      restored.every((p) => /^https?:/i.test(p.url)),
      "restored urls are all http/https",
    ).toBe(true);
  });

  test("the WORKSPACE SET round-trips through reload (all workspaces + layouts + active restored)", async ({
    page,
  }) => {
    // Fresh context → one default workspace (ws-1) seeded with the mock fleet.
    await H.loadHost(page);
    const ws1 = await H.activeWorkspace(page);
    expect(ws1, "default workspace active").toBeTruthy();
    const ws1PanesBefore = await H.panes(page);
    expect(ws1PanesBefore.length, "ws1 has seeded panes").toBeGreaterThanOrEqual(2);
    // Capture ws1's urls BEFORE the reload (ws1 is active here).
    const ws1ParamsBefore = await H.paneParams(page);
    const ws1UrlsBefore = new Set(ws1ParamsBefore.map((p) => p.url));

    // Create a second workspace + add a server pane to it.
    const ws2 = await H.addWorkspace(page);
    expect(ws2, "ws2 created").toBeTruthy();
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws2);
    const ws2Url = H.serverUrl("ws-persist");
    const ws2Pane = await H.addServer(page, ws2Url, "ws-persist");
    expect(ws2Pane, "server pane opened in ws2").toBeTruthy();
    const ws2PanesBefore = await H.panes(page);
    expect(ws2PanesBefore, "ws2 has the added pane").toContain(ws2Pane);

    // Flush the debounced save (both workspaces' layouts + the workspace set).
    await H.waitForSavedLayout(page, ws1PanesBefore.length + ws2PanesBefore.length);

    // Reload → cold restore reads the v2 blob: BOTH workspaces + their layouts +
    // the active workspace are restored.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);

    // The workspace SET round-tripped: both workspace ids survive.
    await expect.poll(async () => (await H.workspaces(page)).sort()).toEqual([ws1, ws2].sort());
    // The active workspace is restored (ws2 was active when we reloaded).
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws2);
    // ws2's pane restored + live.
    await expect.poll(async () => H.panes(page)).toContain(ws2Pane);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // Switch to ws1 → its seeded panes restored too (the layout, not the seed,
    // was persisted — fromJSON recreated them with the same urls/labels).
    await H.setActiveWorkspace(page, ws1!);
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws1);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ws1PanesBefore.length);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
    const ws1Restored = await H.paneParams(page);
    expect(
      ws1Restored.length,
      "ws1 panes restored with the same count",
    ).toBe(ws1PanesBefore.length);
    // Every ws1 url survived the round-trip (fromJSON preserves params).
    for (const r of ws1Restored) {
      expect(ws1UrlsBefore.has(r.url), `ws1 restored url ${r.url} was seeded before`).toBe(true);
    }
  });

  test("maximal workspace clear (to the last-workspace guard) removes a coexisting legacy v2 blob; v3 persists the survivor", async ({ page }) => {
    // SCOPE NOTE (audit item, verified): flushSave's clear-all branch
    // (json === null → BOTH keys removed) is UNREACHABLE through app paths —
    // closeWorkspace refuses to close the last workspace (the never-zero
    // invariant, store.ts) and validatePersistedState rejects empty blobs, so
    // serializeAllFn always reports >= 1 workspace. The code path itself is
    // verified present (layoutPersistence.ts flushSave: the json===null arm
    // removeItem's BOTH the v3 key and the legacy v2 key). What IS reachable
    // — and what this test pins — is the same hygiene at the maximal
    // user-driven clear: close workspaces until the guard refuses, then the
    // post-clear save (a) REMOVES a coexisting legacy v2 blob (the
    // resurrection hazard: readBlob falls back to the v2 key whenever the v3
    // key is absent, so a surviving v2 blob could resurrect stale px
    // geometry) and (b) persists exactly the surviving workspace under v3.
    await H.loadHost(page);
    const ws1 = (await H.workspaces(page))[0];
    const ws1PaneCount = (await H.panes(page)).length;
    expect(ws1PaneCount, "ws1 has seeded panes").toBeGreaterThanOrEqual(2);

    // A second workspace, so a user-driven "clear" has something to close.
    const ws2 = await H.addWorkspace(page, "Doomed");
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws2);
    // Flush the debounced save BEFORE planting the legacy key — a pending
    // save would remove it, firing the assertion's gesture early.
    await H.waitForSavedLayout(page, ws1PaneCount);

    // Plant the DANGEROUS coexistence: a legacy v2 px blob next to the live
    // v3 state (mid-session plant; the module's init blob is already fixed,
    // so only the WRITE side — the next save's legacy-key removal — runs).
    const pxLayout = await H.serialize(page);
    await page.evaluate(
      ({ legacyKey, payload }) => {
        localStorage.setItem(
          legacyKey,
          JSON.stringify({
            activeWorkspaceId: "ws-1",
            workspaces: [{ id: "ws-1", name: "Workspace 1", layout: payload }],
          }),
        );
      },
      { legacyKey: H.LEGACY_LAYOUT_STORAGE_KEY_V2, payload: pxLayout },
    );
    expect(
      await page.evaluate((k) => localStorage.getItem(k), H.LEGACY_LAYOUT_STORAGE_KEY_V2),
      "legacy v2 blob planted",
    ).not.toBeNull();

    // Maximal user-driven clear: close ws2 (applies), then ws1 (REFUSED by
    // the last-workspace guard — the shell never has zero workspaces).
    const closed = await H.closeWorkspace(page, ws2!);
    expect(closed, "non-last workspace closed").toBe(true);
    const refused = await H.closeWorkspace(page, ws1!);
    expect(refused, "last-workspace close refused (never-zero invariant)").toBe(false);
    await expect.poll(async () => H.workspaces(page)).toEqual([ws1]);

    // The post-clear debounced save: the legacy v2 key is REMOVED…
    await expect
      .poll(
        async () =>
          page.evaluate((k) => localStorage.getItem(k), H.LEGACY_LAYOUT_STORAGE_KEY_V2),
        { timeout: 8000 },
      )
      .toBeNull();
    // …and the v3 key holds exactly the surviving workspace (a clear at the
    // guard is still a SAVE, not a wipe — the survivor persists). WRITE-PATH
    // NOTE (2026-08-31): poll the #state= HASH for the survivor, not the
    // localStorage mirror — the mirror is now written SYNCHRONOUSLY at
    // mutation time while the hash stays debounced, and the reload below
    // reads the hash FIRST (a mirror-only wait would reload into the stale
    // pre-clear hash). A hash carrying [ws1] implies the full flushSave ran
    // (v2 key removed + v3 mirror written atomically with it).
    await expect
      .poll(
        async () =>
          page.evaluate(() => {
            const hash = window.location.hash;
            if (!hash || !hash.startsWith("#state=")) return null;
            try {
              const p = JSON.parse(
                decodeURIComponent(hash.slice("#state=".length)),
              ) as { workspaces?: Array<{ id: string }> };
              return (p.workspaces ?? []).map((w) => w.id).sort().join(",");
            } catch {
              return null;
            }
          }),
        { timeout: 8000 },
      )
      .toBe(ws1);

    // Cold reload: the survivor restores from v3 (panes intact); with the
    // legacy key gone there is nothing for readBlob's v2 fallback to
    // resurrect even if the v3 key were later cleared.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect.poll(async () => (await H.workspaces(page)).sort()).toEqual([ws1]);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ws1PaneCount);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
  });
});

// =============================================================================
// Proof-gap closures F1/F2 (card hostweb-layout-restore-proof-gaps, from the
// original /commit-review APPROVED-with-DEFER). The tests above prove pane
// COUNT + ids + urls + labels round-trip; these close what they did NOT:
//
//   F1 — floating/tray round-trip: repairGroups() in layoutPersistence.ts is
//        load-bearing for any layout with a collapsed-to-tray pane, but no test
//        ever persisted one. Collapse parks a pane in a FLOATING GROUP
//        (hostController.collapse: addFloatingGroup, never removePanel), the
//        save side serializes it under floatingGroups, and cold restore runs it
//        through repairGroups → fromJSON → a real floating group again.
//
//   F2 — normalized topology: the round-trip above asserts flat pane identity
//        but NOT the split ARRANGEMENT. Here a NON-DEFAULT arrangement is built
//        and a normalized topology fingerprint (tree + group ids + view order +
//        orientation + per-pane identity, transient geometry excluded) must be
//        byte-identical across the reload.
// =============================================================================

// ---- F2: normalized-topology helpers ----------------------------------------

/** Minimal structural mirror of dockview's serialized grid — only the fields
 *  the topology fingerprint consumes. Transient fields (px size, stored
 *  fraction, visibility, viewport extents, focus) are dropped by the
 *  normalizer, never modeled here. */
interface TopoLeaf {
  type: "leaf";
  data: { id: string; views: string[]; activeView?: string };
  size?: number;
  fraction?: number;
  visible?: boolean;
}
interface TopoBranch {
  type: "branch";
  data: TopoNode[];
  size?: number;
  fraction?: number;
  visible?: boolean;
}
type TopoNode = TopoLeaf | TopoBranch;
interface TopoLayout {
  grid: { root: TopoNode; width?: number; height?: number; orientation?: string };
  panels: Record<
    string,
    { id?: string; params?: { url?: string; label?: string; route?: string } }
  >;
  floatingGroups?: Array<{ data?: { views?: string[] }; grid?: unknown }>;
}

/** Normalize a serialized layout (api.toJSON, px shape) into a deterministic
 *  topology fingerprint string: the branch/leaf tree (group id + per-group
 *  view order), the root orientation, the per-pane {url,label,route} identity
 *  map (sorted keys), and floating-group view membership. EXCLUDED as
 *  transient/session-local: px `size`, stored `fraction`, `visible`, grid
 *  width/height (viewport-dependent), activeGroup / per-group activeView
 *  (focus state), and floating overlay px positions. Fixed literal key order
 *  keeps the string directly comparable with toBe(). */
function normalizeTopology(layout: TopoLayout): string {
  const normNode = (n: TopoNode): unknown => {
    if (n.type === "leaf") return { group: n.data.id, views: [...n.data.views] };
    return { branch: n.data.map(normNode) };
  };
  const panels: Record<string, unknown> = {};
  for (const id of Object.keys(layout.panels).sort()) {
    const p = layout.panels[id];
    panels[id] = {
      id: p.id ?? null,
      url: p.params?.url ?? null,
      label: p.params?.label ?? null,
      route: p.params?.route ?? null,
    };
  }
  const floating = (layout.floatingGroups ?? []).map((fg) =>
    fg.data ? { views: [...(fg.data.views ?? [])] } : { grid: true },
  );
  return JSON.stringify({
    orientation: layout.grid.orientation ?? null,
    root: normNode(layout.grid.root),
    panels,
    floating,
  });
}

/** Count grid leaves (groups) in a serialized tree — the pane-slot count. */
function countLeaves(n: TopoNode): number {
  return n.type === "leaf" ? 1 : n.data.reduce((acc, c) => acc + countLeaves(c), 0);
}

test.describe("layout persistence — proof-gap closures (F1/F2)", () => {
  test("F1: a collapsed (trayed) pane round-trips through reload as a floating pane", async ({
    page,
  }) => {
    await H.loadHost(page);
    const ids = await H.panes(page);
    const victim = ids[ids.length - 1];
    const victimBefore = (await H.paneParams(page)).find((p) => p.id === victim)!;
    const gridBefore = await H.gridPaneCount(page);
    expect(gridBefore, "enough grid panes for the collapse guard").toBeGreaterThanOrEqual(2);

    // Collapse-to-tray through the production path (addFloatingGroup park; the
    // pane stays in api.panels but leaves the grid).
    await H.collapse(page, victim);
    await expect.poll(async () => (await H.trayIds(page)).includes(victim)).toBe(true);
    await expect.poll(async () => H.gridPaneCount(page)).toBe(gridBefore - 1);

    // SAVE-SIDE witness: the debounced save flushed a v3 blob whose layout
    // carries the victim INSIDE floatingGroups. Panel-count polling cannot see
    // a collapse (the count is unchanged) — poll the raw blob instead.
    await expect
      .poll(
        async () =>
          page.evaluate(
            ({ key, victim }) => {
              const raw = localStorage.getItem(key);
              if (!raw) return false;
              try {
                const parsed = JSON.parse(raw) as {
                  workspaces?: Array<{
                    layout?: { floatingGroups?: Array<{ data?: { views?: string[] } }> };
                  }>;
                };
                return (parsed.workspaces ?? []).some((ws) =>
                  (ws.layout?.floatingGroups ?? []).some((fg) =>
                    (fg.data?.views ?? []).includes(victim),
                  ),
                );
              } catch {
                return false;
              }
            },
            { key: H.LAYOUT_STORAGE_KEY, victim },
          ),
        { timeout: 8000 },
      )
      .toBe(true);

    // RELOAD → cold restore. repairGroups() walks the saved floatingGroups; the
    // victim's group survives repair and fromJSON recreates it as a REAL
    // floating group (back in the tray) with its {url,label} intact, off-grid.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ids.length);
    await expect
      .poll(async () => (await H.trayIds(page)).includes(victim), { timeout: 20000 })
      .toBe(true);
    await expect
      .poll(async () => H.gridPaneCount(page), { timeout: 20000 })
      .toBe(gridBefore - 1);

    const victimAfter = (await H.paneParams(page)).find((p) => p.id === victim);
    expect(victimAfter, "trayed pane restored after reload").toBeDefined();
    expect(victimAfter!.url, "trayed pane url round-trips").toBe(victimBefore.url);
    expect(victimAfter!.label, "trayed pane label round-trips").toBe(victimBefore.label);

    // The restored floating group is a REAL floating group: the production
    // restore() op re-docks it into the grid (its guard requires the panel's
    // group location to be "floating") and the re-docked pane goes live.
    await H.restore(page, victim);
    await expect.poll(async () => (await H.trayIds(page)).includes(victim)).toBe(false);
    await expect.poll(async () => H.gridPaneCount(page)).toBe(gridBefore);
    await H.waitForReady(page, victim);
  });

  test("F1 NEGATIVE: a poisoned floating-pane url is dropped by repairGroups on cold restore", async ({
    page,
  }) => {
    await H.loadHost(page);
    const ids = await H.panes(page);
    const victim = ids[ids.length - 1];
    const gridBefore = await H.gridPaneCount(page);
    expect(gridBefore).toBeGreaterThanOrEqual(2);

    await H.collapse(page, victim);
    await expect.poll(async () => (await H.trayIds(page)).includes(victim)).toBe(true);

    // Wait until the save has flushed the floating group, then poison the
    // victim's url IN BOTH mirrors (localStorage v3 + the #state= hash — the
    // same flushSave writes both, and readBlob() reads the hash FIRST, so
    // poisoning only localStorage would be a no-op).
    await expect
      .poll(
        async () =>
          page.evaluate(
            ({ key, victim }) => {
              const raw = localStorage.getItem(key);
              if (!raw) return false;
              try {
                const parsed = JSON.parse(raw) as {
                  workspaces?: Array<{
                    layout?: { floatingGroups?: Array<{ data?: { views?: string[] } }> };
                  }>;
                };
                return (parsed.workspaces ?? []).some((ws) =>
                  (ws.layout?.floatingGroups ?? []).some((fg) =>
                    (fg.data?.views ?? []).includes(victim),
                  ),
                );
              } catch {
                return false;
              }
            },
            { key: H.LAYOUT_STORAGE_KEY, victim },
          ),
        { timeout: 8000 },
      )
      .toBe(true);
    await page.evaluate(
      ({ key, victim }) => {
        const raw = localStorage.getItem(key);
        if (!raw) throw new Error("no saved layout blob to poison");
        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            layout?: { panels?: Record<string, { params?: unknown }> };
          }>;
        };
        for (const ws of parsed.workspaces ?? []) {
          const panels = ws.layout?.panels;
          if (panels && victim in panels) {
            panels[victim].params = { url: "javascript:alert(document.domain)", label: "evil" };
          }
        }
        const json = JSON.stringify(parsed);
        localStorage.setItem(key, json);
        // Mirror the poison into the URL hash exactly like flushSave would.
        // history.replaceState fires no hashchange (no runtime listener is
        // involved; the hash is read once, at module init on cold load).
        window.history.replaceState(
          null,
          "",
          window.location.pathname +
            window.location.search +
            "#state=" +
            encodeURIComponent(json),
        );
      },
      { key: H.LAYOUT_STORAGE_KEY, victim },
    );

    // Cold restore: isFleetEntry rejects the javascript: url → the victim is
    // not in validRestoreIds → repairGroups drops the now-empty floating group
    // (tray empty), while every valid GRID pane survives untouched.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ids.length - 1);
    await expect.poll(async () => H.trayIds(page), { timeout: 20000 }).toEqual([]);
    await expect
      .poll(async () => H.gridPaneCount(page), { timeout: 20000 })
      .toBe(gridBefore - 1);

    const restored = await H.paneParams(page);
    expect(
      restored.find((p) => p.id === victim),
      "poisoned floating pane was not restored",
    ).toBeUndefined();
    expect(
      (await H.iframeSrcs(page)).every((s) => !/^javascript:/i.test(s)),
      "no javascript: iframe src after poisoned floating restore",
    ).toBe(true);
  });

  test("F2: the split ARRANGEMENT round-trips — normalized grid topology unchanged across reload", async ({
    page,
  }) => {
    await H.loadHost(page);

    // The fresh-seed arrangement — what a NON-persisted cold load would fall
    // back to. The round-tripped topology must differ from it (non-default).
    const seedTopology = normalizeTopology((await H.serialize(page)) as unknown as TopoLayout);

    // Build a NON-DEFAULT arrangement: split right off pane-1, then split the
    // NEW pane DOWN — nesting a vertical branch inside the root branch.
    const ids = await H.panes(page);
    const mid = await H.split(page, ids[0], "right");
    expect(mid, "first split created a pane").toBeTruthy();
    await H.waitForReady(page, mid!);
    const deep = await H.split(page, mid!, "down");
    expect(deep, "second split created a pane").toBeTruthy();
    await H.waitForReady(page, deep!);

    const beforeLayout = (await H.serialize(page)) as unknown as TopoLayout;
    const before = normalizeTopology(beforeLayout);
    const total = ids.length + 2;
    expect((await H.panes(page)).length, "two new panes exist").toBe(total);
    expect(
      countLeaves(beforeLayout.grid.root),
      "each pane owns a grid leaf (group)",
    ).toBe(total);
    expect(
      before,
      "arrangement is non-default (differs from the fresh seed topology)",
    ).not.toBe(seedTopology);

    // Flush the debounced save, then cold-reload.
    await H.waitForSavedLayout(page, total);
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(total);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // The normalized topology — tree structure + group ids + per-group view
    // order + root orientation + per-pane identity + floating membership — is
    // IDENTICAL across the reload (transient geometry excluded by design).
    const after = normalizeTopology((await H.serialize(page)) as unknown as TopoLayout);
    expect(after, "normalized topology round-trips through reload").toBe(before);
  });
});

