import { test, expect } from "@playwright/test";
import * as H from "./util";

// =============================================================================
// Layout-persistence regression gate (multi-workspace v3 fractional schema) —
// proves the Dockview tiling round-trips through a page reload AND that a
// poisoned saved layout is rejected.
//
// Mechanism under test (src/dockview/layoutPersistence.ts):
//   SAVE   — debounced, serializes EVERY workspace's api.toJSON() into the v3
//            blob localStorage["vh-host:layout:v3"] =
//              { v: 3, activeWorkspaceId, workspaces: [{id, name, layout}] }
//            where each grid child stores `fraction` (share of its parent
//            branch) instead of dockview's px `size`; hooked on any
//            workspace's onDidLayoutChange + workspace add/close/switch.
//   RESTORE — cold init reads the v3 blob (hash → v3 key → legacy v2 key,
//            migrating px→fractions in-memory), materializes px = fraction ×
//            the CURRENT container extent, validates every workspace's every
//            pane url through the SAME isFleetEntry http/https guard the fleet
//            resolver uses, REPAIRS (drops invalid panes per workspace), and
//            calls api.fromJSON() exactly ONCE PER WORKSPACE (COLD ONLY — it
//            reloads every iframe in that workspace; runtime never calls it).
//
// PRECEDENCE under test: saved-layout-wins-with-validation; fleet/mock seed is
// the fallback for the default workspace when no valid blob exists.
//
// Playwright gives each test() a fresh browser context, so localStorage is EMPTY
// at the start of every test unless a test explicitly pre-seeds it. The
// survival/shell gates therefore see no blob and cold restore falls back to
// seed — they are unaffected (verified separately).
//
// Runs on Chromium AND Firefox (webkit is launch-blocked locally; see the default
// lane's project set).
// =============================================================================

/** Wrap a serialized Dockview layout in the workspace envelope as the default
 *  workspace (ws-1), so a pre-seeded blob matches what the app cold-restores.
 *  The default workspace id on a fresh context is "ws-1" (nextWsId starts at 1).
 *  Deliberately carries NO `v: 3` marker — the payload is raw dockview px
 *  output, exactly like a legacy v2-era blob, so the read path MIGRATES it
 *  (px→fractions) like real legacy data while keeping this test otherwise
 *  structurally valid (the poison test rejects for the POISON, not shape). */
function wrapLayout(layout: Record<string, unknown>): {
  activeWorkspaceId: string;
  workspaces: Array<{ id: string; name: string; layout: Record<string, unknown> }>;
} {
  return {
    activeWorkspaceId: "ws-1",
    workspaces: [{ id: "ws-1", name: "Workspace 1", layout }],
  };
}

test.describe("layout persistence", () => {
  test("saved layout round-trips through reload (panes restored with same urls/labels)", async ({
    page,
  }) => {
    // Fresh context → no localStorage → seed loads as today.
    await H.loadHost(page);

    // Mutate the layout so the persisted state differs from the default seed (a
    // split adds a pane whose {url,label} is generated by nextMockPane).
    const seedIds = await H.panes(page);
    const newId = await H.split(page, seedIds[0], "right");
    expect(newId, "split created a new pane").toBeTruthy();
    await H.waitForReady(page, newId!);

    // Capture the post-mutation layout — the state we expect to persist.
    const expected = await H.paneParams(page);
    const expectedById = new Map(expected.map((p) => [p.id, p]));
    expect(expected.length, "layout has the split pane").toBe(seedIds.length + 1);

    // Flush the debounced save to localStorage before reloading.
    await H.waitForSavedLayout(page, expected.length);

    // Reload → cold restore reads localStorage (fromJSON, exactly once per ws).
    // The restored iframes are FRESH (fromJSON recreates them) — that is allowed
    // here because this is cold init, before any iframe had a live identity.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(expected.length);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
    const restored = await H.paneParams(page);

    // The restored layout matches: same pane count + every restored id carries
    // the exact {url,label} it had before the reload (ids are stable across
    // fromJSON — dockview's deserializer reuses the saved panel ids verbatim).
    expect(restored.length, "restored pane count matches").toBe(expected.length);
    for (const r of restored) {
      const e = expectedById.get(r.id);
      expect(e, `restored pane ${r.id} existed before reload`).toBeDefined();
      expect(r.url, `restored pane ${r.id} url unchanged`).toBe(e!.url);
      expect(r.label, `restored pane ${r.id} label unchanged`).toBe(e!.label);
    }
  });

  test("NEGATIVE: a poisoned saved layout (javascript: url) is rejected on cold restore", async ({
    page,
  }) => {
    // Start from a REAL, well-formed layout (captured from the live api) so the
    // poisoned blob is otherwise structurally valid — the restore must reject it
    // for the POISON, not for a shape defect. A hand-rolled tree would conflate
    // the two failure modes.
    await H.loadHost(page);
    const state = await H.serialize(page);
    const panels = (state.panels ?? {}) as Record<
      string,
      { params?: { url?: string; label?: string } }
    >;
    const ids = Object.keys(panels);
    expect(ids.length, "seed layout has panels to poison").toBeGreaterThanOrEqual(2);

    // Poison ONE panel's url with a javascript: scheme. This MUST NEVER reach an
    // unsandboxed iframe.src — it would execute same-origin against the host
    // shell. The restore must DROP this panel (defense-in-depth: never trust
    // stored data; the url goes to an unsandboxed iframe.src).
    const victim = ids[ids.length - 1];
    panels[victim].params = { url: "javascript:alert(document.domain)", label: "evil" };

    // Wrap in the workspace envelope (default workspace ws-1) so the app
    // cold-restores this workspace, then pre-seed it into the host origin's
    // localStorage. (addInitScript is avoided because it also runs in every
    // child iframe — the cross-origin mock panes on :5174 — which is the wrong
    // origin; writing on the live :5173 page then reloading is unambiguous and
    // scopes to the host origin only.)
    const payload = wrapLayout(state);
    await page.evaluate(
      ({ payload, key }) => {
        localStorage.setItem(key, JSON.stringify(payload));
      },
      { payload, key: H.LAYOUT_STORAGE_KEY },
    );

    // Cold load: the poisoned panel is DROPPED by restore validation; the
    // remaining valid panels are restored (mirrors the F1 fleet-guard pattern:
    // drop the bad entry, keep the good ones; fall back to seed only if that
    // empties it).
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ids.length - 1);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // SECURITY: no iframe points at the poisoned url (or any non-http scheme).
    const srcs = await H.iframeSrcs(page);
    expect(
      srcs.every((s) => !/^javascript:/i.test(s)),
      "no javascript: iframe src after poisoned restore",
    ).toBe(true);

    // The poisoned panel was dropped; every restored url is http/https.
    const restored = await H.paneParams(page);
    expect(
      restored.find((p) => p.id === victim),
      "poisoned panel was not restored",
    ).toBeUndefined();
    expect(
      restored.every((p) => /^https?:/i.test(p.url)),
      "restored urls are all http/https",
    ).toBe(true);
  });

  test("the WORKSPACE SET round-trips through reload (all workspaces + layouts + active restored)", async ({
    page,
  }) => {
    // Fresh context → one default workspace (ws-1) seeded with the mock fleet.
    await H.loadHost(page);
    const ws1 = await H.activeWorkspace(page);
    expect(ws1, "default workspace active").toBeTruthy();
    const ws1PanesBefore = await H.panes(page);
    expect(ws1PanesBefore.length, "ws1 has seeded panes").toBeGreaterThanOrEqual(2);
    // Capture ws1's urls BEFORE the reload (ws1 is active here).
    const ws1ParamsBefore = await H.paneParams(page);
    const ws1UrlsBefore = new Set(ws1ParamsBefore.map((p) => p.url));

    // Create a second workspace + add a server pane to it.
    const ws2 = await H.addWorkspace(page);
    expect(ws2, "ws2 created").toBeTruthy();
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws2);
    const ws2Url = H.serverUrl("ws-persist");
    const ws2Pane = await H.addServer(page, ws2Url, "ws-persist");
    expect(ws2Pane, "server pane opened in ws2").toBeTruthy();
    const ws2PanesBefore = await H.panes(page);
    expect(ws2PanesBefore, "ws2 has the added pane").toContain(ws2Pane);

    // Flush the debounced save (both workspaces' layouts + the workspace set).
    await H.waitForSavedLayout(page, ws1PanesBefore.length + ws2PanesBefore.length);

    // Reload → cold restore reads the v2 blob: BOTH workspaces + their layouts +
    // the active workspace are restored.
    await page.reload();
    await expect.poll(async () => H.connected(page), { timeout: 20000 }).toBe(true);

    // The workspace SET round-tripped: both workspace ids survive.
    await expect.poll(async () => (await H.workspaces(page)).sort()).toEqual([ws1, ws2].sort());
    // The active workspace is restored (ws2 was active when we reloaded).
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws2);
    // ws2's pane restored + live.
    await expect.poll(async () => H.panes(page)).toContain(ws2Pane);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);

    // Switch to ws1 → its seeded panes restored too (the layout, not the seed,
    // was persisted — fromJSON recreated them with the same urls/labels).
    await H.setActiveWorkspace(page, ws1!);
    await expect.poll(async () => H.activeWorkspace(page)).toBe(ws1);
    await expect
      .poll(async () => (await H.panes(page)).length, { timeout: 20000 })
      .toBe(ws1PanesBefore.length);
    for (const id of await H.panes(page)) await H.waitForReady(page, id);
    const ws1Restored = await H.paneParams(page);
    expect(
      ws1Restored.length,
      "ws1 panes restored with the same count",
    ).toBe(ws1PanesBefore.length);
    // Every ws1 url survived the round-trip (fromJSON preserves params).
    for (const r of ws1Restored) {
      expect(ws1UrlsBefore.has(r.url), `ws1 restored url ${r.url} was seeded before`).toBe(true);
    }
  });
});

